services:
  - type: web
    name: codenexus-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        sync: false
      - key: GEN_AI_SECRET
        sync: false
      - key: ZENROWS_API_KEY
        sync: false
